build:
 options:
    logging: CLOUD_LOGGING_ONLY
 steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'docker.pkg.dev/test-project-509009/test-hello-world-repo/hello-world:$SHORT_SHA'
    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'docker.pkg.dev/test-project-509009/test-hello-world-repo/hello-world:$SHORT_SHA'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'hello-world'
    - '--image'
    - 'docker.pkg.dev/test-project-509009/test-hello-world-repo/hello-world:$SHORT_SHA'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

images:
- 'docker.pkg.dev/test-project-509009/test-hello-world-repo/hello-world:$SHORT_SHA'
