steps:

# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-south-1-docker.pkg.dev/test-project-509009/test-hello-world-repo/hello-world:$SHORT_SHA'
    - '.'

# Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '$asia-south-1-docker.pkg.dev/test-project-509009/test-hello-world-repo/hello-world:$SHORT_SHA'

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'hello-world'
    - '--image'
    - 'asia-south-1-docker.pkg.dev/test-project-509009/test-hello-world-repo/hello-world:$SHORT_SHA'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

images:
- 'asia-south-1-docker.pkg.dev/test-project-509009/test-hello-world-repo/hello-world:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY

